///<amd-dependency path="./AlertsAndMessagesDirective" />
///<amd-dependency path="./BindTemplateDirective" />
///<amd-dependency path="./BreadcrumbsPanelDirective" />
///<amd-dependency path="./CellShowOptionsDirective" />
///<amd-dependency path="./CkEditorDirective" />
///<amd-dependency path="./CollectionUpdatesDirective" />
///<amd-dependency path="./FileReadDirective" />
///<amd-dependency path="./LanguagesPanelDirective" />
///<amd-dependency path="./LoginDialogDirective" />
///<amd-dependency path="./MultiFileReadDirective" />
///<amd-dependency path="./NavigationTreeDirective" />
///<amd-dependency path="./NodeLinkDirective" />
///<amd-dependency path="./ScrollSpySideDirective" />
///<amd-dependency path="./ScrollSpyTopDirective" />
///<amd-dependency path="./SearchPanelDirective" />
///<amd-dependency path="./ToolbarPanelDirective" />
///<amd-dependency path="./UserPanelDirective" />

import ng = require('angular');
