/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.lessmarkup.dataobjects;

import com.lessmarkup.interfaces.data.AbstractDataObject;
import com.lessmarkup.interfaces.recordmodel.RequiredField;

import java.time.OffsetDateTime;
import java.util.OptionalLong;

public class User extends AbstractDataObject {
    private boolean removed;
    private boolean blocked;
    private String blockReason;
    @RequiredField
    private String name;
    @RequiredField
    private String email;
    private String salt;
    private String password;
    private String passwordChangeToken;
    private OffsetDateTime passwordChangeTokenExpires;
    private boolean administrator;
    private OffsetDateTime registered;
    private boolean approved;
    private boolean emailConfirmed;
    private boolean passwordAutoGenerated;
    private OffsetDateTime lastLogin;
    private OffsetDateTime lastBlock;
    private OffsetDateTime lastPasswordChanged;
    private OffsetDateTime lastActivity;
    private OffsetDateTime registrationExpires;
    private OffsetDateTime unblockTime;
    private String lockReason;
    private String validateSecret;
    private boolean requiresPasswordReset;
    private OptionalLong avatarImageId;
    private OptionalLong userImageId;
    private String title;
    private String signature;
    private boolean showEmail;
    private int multiFactorAuthorization;
    private String authProvider;
    private String authProviderUserId;
    private String settings;
    private String properties;

    public boolean isRemoved() {
        return removed;
    }
    public void setRemoved(boolean isRemoved) {
        this.removed = isRemoved;
    }

    public boolean isBlocked() {
        return blocked;
    }
    public void setBlocked(boolean isBlocked) { this.blocked = isBlocked; }

    public String getBlockReason() {
        return blockReason;
    }
    public void setBlockReason(String blockReason) {
        this.blockReason = blockReason;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    public String getSalt() {
        return salt;
    }
    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public String getPasswordChangeToken() {
        return passwordChangeToken;
    }
    public void setPasswordChangeToken(String passwordChangeToken) {
        this.passwordChangeToken = passwordChangeToken;
    }

    public OffsetDateTime getPasswordChangeTokenExpires() {
        return passwordChangeTokenExpires;
    }
    public void setPasswordChangeTokenExpires(OffsetDateTime passwordChangeTokenExpires) { this.passwordChangeTokenExpires = passwordChangeTokenExpires; }

    public boolean isAdministrator() {
        return administrator;
    }
    public void setAdministrator(boolean administrator) {
        this.administrator = administrator;
    }

    public OffsetDateTime getRegistered() {
        return registered;
    }
    public void setRegistered(OffsetDateTime registered) {
        this.registered = registered;
    }

    public boolean isApproved() {
        return approved;
    }
    public void setApproved(boolean approved) {
        this.approved = approved;
    }

    public boolean isEmailConfirmed() {
        return emailConfirmed;
    }
    public void setEmailConfirmed(boolean emailConfirmed) {
        this.emailConfirmed = emailConfirmed;
    }

    public boolean isPasswordAutoGenerated() {
        return passwordAutoGenerated;
    }
    public void setPasswordAutoGenerated(boolean passwordAutoGenerated) { this.passwordAutoGenerated = passwordAutoGenerated; }

    public OffsetDateTime getLastLogin() {
        return lastLogin;
    }
    public void setLastLogin(OffsetDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    public OffsetDateTime getLastBlock() {
        return lastBlock;
    }
    public void setLastBlock(OffsetDateTime lastBlock) {
        this.lastBlock = lastBlock;
    }

    public OffsetDateTime getLastPasswordChanged() {
        return lastPasswordChanged;
    }
    public void setLastPasswordChanged(OffsetDateTime lastPasswordChanged) { this.lastPasswordChanged = lastPasswordChanged; }

    public OffsetDateTime getLastActivity() {
        return lastActivity;
    }
    public void setLastActivity(OffsetDateTime lastActivity) {
        this.lastActivity = lastActivity;
    }

    public OffsetDateTime getRegistrationExpires() {
        return registrationExpires;
    }
    public void setRegistrationExpires(OffsetDateTime registrationExpires) { this.registrationExpires = registrationExpires; }

    public OffsetDateTime getUnblockTime() {
        return unblockTime;
    }
    public void setUnblockTime(OffsetDateTime unblockTime) {
        this.unblockTime = unblockTime;
    }

    public String getLockReason() {
        return lockReason;
    }
    public void setLockReason(String lockReason) {
        this.lockReason = lockReason;
    }

    public String getValidateSecret() {
        return validateSecret;
    }
    public void setValidateSecret(String validateSecret) {
        this.validateSecret = validateSecret;
    }

    public boolean isRequiresPasswordReset() {
        return requiresPasswordReset;
    }
    public void setRequiresPasswordReset(boolean requiresPasswordReset) { this.requiresPasswordReset = requiresPasswordReset; }

    public OptionalLong getAvatarImageId() {
        return avatarImageId;
    }
    public void setAvatarImageId(OptionalLong avatarImageId) {
        this.avatarImageId = avatarImageId;
    }

    public OptionalLong getUserImageId() {
        return userImageId;
    }
    public void setUserImageId(OptionalLong userImageId) {
        this.userImageId = userImageId;
    }

    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public String getSignature() {
        return signature;
    }
    public void setSignature(String signature) {
        this.signature = signature;
    }

    public boolean isShowEmail() {
        return showEmail;
    }
    public void setShowEmail(boolean showEmail) {
        this.showEmail = showEmail;
    }

    public int getMultiFactorAuthorization() {
        return multiFactorAuthorization;
    }
    public void setMultiFactorAuthorization(int multiFactorAuthorization) { this.multiFactorAuthorization = multiFactorAuthorization; }

    public String getAuthProvider() {
        return authProvider;
    }
    public void setAuthProvider(String authProvider) {
        this.authProvider = authProvider;
    }

    public String getAuthProviderUserId() {
        return authProviderUserId;
    }
    public void setAuthProviderUserId(String authProviderUserId) {
        this.authProviderUserId = authProviderUserId;
    }

    public String getSettings() {
        return settings;
    }
    public void setSettings(String settings) {
        this.settings = settings;
    }

    public String getProperties() {
        return properties;
    }
    public void setProperties(String properties) {
        this.properties = properties;
    }
}
