/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.lessmarkup.dataobjects

import java.time.OffsetDateTime

import com.lessmarkup.interfaces.annotations.RequiredField
import com.lessmarkup.interfaces.data.{OptionString, OptionOffsetDateTime, DataObject, OptionLong}

class User(
  id: Long = 0,
  var removed: Boolean = false,
  var blocked: Boolean = false,
  var blockReason: OptionString = None,
  @RequiredField
  var name: String,
  @RequiredField
  var email: String,
  var salt: String,
  var password: String,
  var passwordChangeToken: Option[String] = None,
  var passwordChangeTokenExpires: OptionOffsetDateTime = None,
  var administrator: Boolean = false,
  var registered: OffsetDateTime,
  var approved: Boolean = false,
  var emailConfirmed: Boolean = false,
  var passwordAutoGenerated: Boolean = false,
  var lastLogin: OffsetDateTime,
  var lastBlock: OptionOffsetDateTime = None,
  var lastPasswordChanged: OptionOffsetDateTime = None,
  var lastActivity: OffsetDateTime,
  var registrationExpires: OptionOffsetDateTime = None,
  var unblockTime: OptionOffsetDateTime = None,
  var lockReason: Option[String] = None,
  var validateSecret: Option[String] = None,
  var requiresPasswordReset: Boolean = false,
  var avatarImageId: OptionLong = None,
  var userImageId: OptionLong = None,
  var title: Option[String] = None,
  var signature: Option[String] = None,
  var showEmail: Boolean = false,
  var multiFactorAuthorization: Int = 0,
  var authProvider: Option[String] = None,
  var authProviderUserId: Option[String] = None,
  var settings: Option[String] = None,
  var properties: Option[String] = None
  ) extends DataObject(id)
