package com.lessmarkup.interfaces.system;

public interface EngineConfiguration {
    boolean isSafeMode();
    void setSafeMode(boolean safeMode);
    String getFatalErrorsEmail();
    void setFatalErrorsEmail(String email);
    boolean isSmtpConfigured();
    String getSmtpServer();
    void setSmtpServer(String server);
    String getSmtpUsername();
    void setSmtpUsername(String name);
    String getSmtpPassword();
    void setSmtpPassword(String password);
    boolean isSmtpSsl();
    void setSmtpSsl(boolean ssl);
    String getRecaptchaPublicKey();
    void setRecaptchaPublicKey(String key);
    String getRecaptchaPrivateKey();
    void setRecaptchaPrivateKey(String key);
    boolean isUseTestMail();
    void setUseTestMail(boolean use);
    String getNoReplyEmail();
    void setNoReplyEmail(String email);
    String getNoReplyName();
    void setNoReplyName(String name);
    int getFailedAttemptsRememberMinutes();
    void setFailedAttemptsRememberMinutes(int minutes);
    int getMaximumFailedAttempts();
    void setMaximumFailedAttempts(int attempts);
    int getRecordsPerPage();
    void setRecordsPerPage(int recordsPerPage);
    String getAuthCookieName();
    void setAuthCookieName(String name);
    int getAuthCookieTimeout();
    void setAuthCookieTimeout(int timeout);
    String getAuthCookiePath();
    void setAuthCookiePath(String path);
    boolean isAutoRefresh();
    void setAutoRefresh(boolean autoRefresh);
    String getNoAdminName();
    void setNoAdminName(String noAdminName);
    int getBackgroundJobInterval();
    void setBackgroundJobInterval(int interval);
    String getAdminLoginPage();
    void setAdminLoginPage(String adminLoginPage);
    String getAdminLoginAddress();
    void setAdminLoginAddress(String adminLoginAddress);
    boolean isMigrateDataLossAllowed();
    void setMigrateDataLossAllowed(boolean migrateDataLossAllowed);
    boolean isCustomizationsDisabled();
    void setCustomizationsDisabled(boolean customizationsDisabled);
    String getConnectionString();
    void setConnectionString(String connectionString);
    String getModulesPath();
    void setModulesPath(String modulesPath);
    String getSessionKey();
    void setSessionKey(String sessionKey);
}
